#' Writes a README file
#'
#' @description write.readMe writes a readme file based on the current metadata
#'
#' @details write.readMe writes a mock-up of the readme file that will eventually be automatically generated by DataStore. This file is for error checking purposes only. If something looks off, you can go back and fix your metadata to correct it but you should not upload this readme file with your data package.
#'
#' @param emlObject is an R object imported (typically from an EML-formatted .xml file) using EML::read_eml(<filename>, from="xml").
#' @param outfile is the name of the file you want to write, typically *.txt.
#'
#' @return a character sting in readable format (saved to the given outfile)
#' @export
#'
#' @examples
#'  \dontrun{
#' write.readMe(emlObject, "TestReadMe.txt")
#' }
write.readMe<-function(emlObject, outfile){

  #get components:
  Ref<-get.DSRefID(emlObject) #Data Store Ref. ID
  doi<-get.DOI(emlObject) #DOI
  title<-get.title(emlObject) #title
  abstract<-get.abstract(emlObject) #abstract
  fileInfo<-get.fileInfo(emlObject) #names, sizes, descriptions
  start<-get.beginDate(emlObject) #content start date
  end<-get.endDate(emlObject) #content end date
  units<-get.parkUnits(emlObject) #park units where data were collected
  CUI<-get.CUI(emlObject) #controlled unclassified information status
  DRRdoi<-get.DRRdoi(emlObject) #DOI of accompanying DRR
  citation<-get.citation(emlObject) #citation

  #Write to the components to the text file specified in "outfile".
  cat(paste0("ReadMe file for DataStore reference# ", Ref), file=outfile, sep="\n")

  cat(paste0("Digital Object Identifier (DOI): ", doi, "\n"), file=outfile, sep="\n", append=TRUE)

  cat("Title:", file=outfile, sep="\n", append=TRUE)

  cat(paste0(title, "\n"), file=outfile, sep="\n", append=TRUE)

  cat("Abstract:", file=outfile, sep="\n", append=TRUE)

  cat(abstract, file=outfile, sep="\n", append=TRUE)

  cat(paste0("\n", "Files:"), file=outfile, sep="\n", append=TRUE)

  cat(stargazer::stargazer(fileInfo, summary=FALSE, type="text"), file=outfile, sep="\n", append=TRUE)

  cat("\nContent:", file=outfile, sep="\n", append=TRUE)

  cat(paste0("Begin date: ", start), file=outfile, sep="\n", append=TRUE)

  cat(paste0("End date: ", end), file=outfile, sep="\n", append=TRUE)

  if(!is.na(units)){
  cat(units, file=outfile, sep="\n", append=TRUE)}
  if(is.na(units)){
    cat(paste0("Park Unit Connections: ", units), file=outfile, sep="\n", append=TRUE)
  }

  cat(paste0("Sensitivity: ", CUI), file=outfile, sep="\n", append=TRUE)

  cat(paste0("Data Quality: Information about production and quality of this product can be found in the Data Release Report (DRR) at: ", DRRdoi, "\n"), file=outfile, sep="\n", append=TRUE)

  cat("\nCitation:\n", file=outfile, sep="\n", append=TRUE)

  cat(citation, file=outfile, sep="\n", append=TRUE)
}

